name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        type: string
        required: false
        default: ''
      newVersion:
        description: 'New Version'
        type: string
        required: false
        default: ''

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configure build steps as you'd normally do

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Git
        run: /usr/bin/git config user.email "notifications@github.com";/usr/bin/git config user.name "GitHub Actions"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      # Patch version numbers and create tag
      - name: Gradle Release
        run: |
          gradle release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ inputs.releaseVersion }} -Prelease.newVersion=${{ inputs.newVersion }}
